repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: fmt-check
        name: fmt-check
        entry: nix-shell --run 'just pre-commit'
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pre-push
        name: pre-push
        entry: nix-shell --run 'just pre-push'
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: commitlint
        name: commitlint
        entry: npx --no-install commitlint --edit
        language: system
        stages: [commit-msg]
